---
  - hosts: webserver
    become: true
    tasks:
      - name: install unzip
        apt: name=unzip state=present update_cache=yes

      - name: install perl
        apt: name=libwww-perl state=present update_cache=yes

      - name: install perl
        apt: name=libdatetime-perl state=present update_cache=yes

      - name: create directory for scripts
        file: path=/home/ubuntu/monitoring state=directory

      - name: download monitoring scripts
        get_url: dest=/home/ubuntu/monitoring url=http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip

      - name: unzip scripts
        unarchive: src=/home/ubuntu/monitoring/*.zip dest=/home/ubuntu/monitoring

      - name: copy custom monitoring script to webserver
        copy: src=custom-script.sh force=yes /home/ubuntu/monitoring

      - name: change permission to the script
        file: path=/home/ubuntu/monitoring/custom-script.sh mode="u+x"

      - name: setup cronjob to monitor disk usage every minute
        cron: minute="*/5" name="monitor disk usage" user="root" job="/home/ubuntu/monitoring/custom-script.sh"
