---
  - hosts: webserver
    become: true
    tasks:
      - name: install nginx
        yum: name=nginx state=latest update_cache=yes
        notify:
          - start nginx

    handlers:
      - name: start nginx
        service: name=nginx state=started
